### ISSUE TITLE
core dump

### ISSUE THREAD

**Issue by liufuda** [eProsima/DDS-Record-Replay#105]
I am encountering an issue with a core dump when my IDL file includes an enumeration type definition, and I have created a corresponding DataWriter in my C++ program. When running this program and attempting to run DDS Recorder, I intermittently experience a core dump.
I am certain that the enumeration type is causing the issue. If I do not use an enumeration type, a core dump does not occur.

test step
1. run c++ program which create a datawrite,and keep it run.
2. run the shell script
```
 #!/bin/bash
origin_path=`pwd`
count=1
source /opt/FastDDS/DDS-Record-Replay/local_setup.sh
until [ $count -gt 100 ]; do
    sleep 1
    nohup /opt/FastDDS/DDS-Record-Replay/ddsrecorder_tool/bin/ddsrecorder -d -c ../data/config/recorder_config.yaml>/dev/null 2>&1 &
    sleep 1
    pkill -SIGINT -u $(whoami) ddsrecorder
    echo "Iteration $count"
    ((count++))
done
cd ${origin_path}
```
![image](https://github.com/eProsima/DDS-Record-Replay/assets/20452101/9ea96860-19e3-4fc9-9af7-ec78637f6676)

**Comment by liufuda** [comment]
ddsrecorder version:
![image](https://github.com/eProsima/DDS-Record-Replay/assets/20452101/cf160fc8-0264-4167-b3a8-e22674a7c3f3)

**Comment by liufuda** [comment]
my idl fiel define as follow
```
enum TEST_ENUM {
    TEST_ENUM_0, /* 0 */
    TEST_ENUM_1,
    TEST_ENUM_2
};

struct test {
    TEST_ENUM id;
};
```
generate test proj with cmd:
```
fastddsgen  -example CMake -typeobject test.idl
```
then add registertestTypes() to testPubSubMain.cxx
![image](https://github.com/eProsima/DDS-Record-Replay/assets/20452101/2a77b20a-ff5f-4584-9de8-dfb34e351393)

**Comment by juanlofer-eprosima** [comment]
Hi @liufuda , thanks for reaching out.

We tried to replicate the issue but it did work well in our environment. Make sure you are compiling against Fast-DDS's `bugfix/complex-dynamic-types` branch, and also double check [Configuring Fast DDS DynamicTypes](https://dds-recorder.readthedocs.io/en/latest/rst/tutorials/dynamic_types.html#configuring-fast-dds-dynamictypes) tutorial, as you might be missing the following:

> // Send type information so the type can be discovered
    type->auto_fill_type_information(true);
    type->auto_fill_type_object(false);

> pqos.wire_protocol().builtin.typelookup_config.use_client = false;
    pqos.wire_protocol().builtin.typelookup_config.use_server = true;

We will try to improve at some point Fast-DDS-Gen example generation utility, so that these changes do not need to be manually applied when using `-typeobject` option.

**Comment by liufuda** [comment]
hi@juanlofer-eprosima， I guess the reason you didn't replicate it is due to a lack of/ Data/configuration/recorder_ Config.yaml file, you can modify the test script as follow
```shell
 #!/bin/bash
origin_path=`pwd`
count=1
source /opt/FastDDS/DDS-Record-Replay/local_setup.sh
until [ $count -gt 100 ]; do
    sleep 1
    nohup /opt/FastDDS/DDS-Record-Replay/ddsrecorder_tool/bin/ddsrecorder >/dev/null 2>&1 &
    sleep 1
    pkill -SIGINT -u $(whoami) ddsrecorder
    echo "Iteration $count"
    ((count++))
done
cd ${origin_path}
```

**Comment by liufuda** [comment]
Add the following code to my program,core dump miss
```C++ 
// Send type information so the type can be discovered
type->auto_fill_type_information(true);
type->auto_fill_type_object(false);

pqos.wire_protocol().builtin.typelookup_config.use_client = false;
pqos.wire_protocol().builtin.typelookup_config.use_server = true;
```
