### ISSUE TITLE
main v0.3.0 does not build

### ISSUE THREAD

**Issue by paulBismuthListen** [eProsima/DDS-Record-Replay#122]
hello,

main does not build because it tries to build fastcdr / fastrtps v1 and v2.

I think this is because:
In cmake_utils/cmake/compilation/compile_library.cmake
```
        if ("${ARGV2}" STREQUAL "")
            file(
                GLOB_RECURSE SOURCES_FILES
                    "${_SOURCE_PATH}/*.c"
                    "${_SOURCE_PATH}/*.cpp"
                    "${_SOURCE_PATH}/*.cxx"
                    "${_SOURCE_PATH}/**/*.c"
                    "${_SOURCE_PATH}/**/*.cpp"
                    "${_SOURCE_PATH}/**/*.cxx"
```
so when calling:
```
# Compile C++ library
compile_library(
    "${PROJECT_SOURCE_DIR}/src/cpp" # Source directory
    "${PROJECT_SOURCE_DIR}/include" # Include directory
    "${SOURCES_FILES}"
    "${HEADERS_FILES}"
)
```

it will also get the files under V1 and V2 at compile time.

**Comment by rsanchez15** [comment]
Hi @paulBismuthListen

Which version of Fast CDR and Fast DDS are you using?

**Comment by paulBismuthListen** [comment]
Hello i am using fasttps-2.13.1 and fastcdr-2.1.3.

Though isssue is that at compile time cmake tries to compile both files in V1 and files in V2:
`build/DDS-Record-Replay-0.3.0/ddsrecorder_participants/src/cpp/common/types/v1/DynamicTypesCollectionPubSubTypes.cpp:222:49: error: ‘class eprosima::fastcdr::Cdr’ has no member named ‘getSerializedDataLength’; did you mean ‘get_serialized_data_length’?
     payload->length = static_cast<uint32_t>(ser.getSerializedDataLength());`

Which was strange to me so decided to go for a little message(STATUS ...).

In ./ddsrecorder_participants fastrtps version is correctly detected and both list HEADERS_FILE and SOURCE_FILES seems correct to me:

```

-- ------------HEADERS: /build/DDS-Record-Replay-0.3.0/ddsrecorder_participants/include/ddsrecorder_participants/constants.hpp
-- ------------SOURCES: /build/DDS-Record-Replay-0.3.0/ddsrecorder_participants/src/cpp/common/types/v2/DynamicTypesCollection.cpp;
/build/DDS-Record-Replay-0.3.0/ddsrecorder_participants/src/cpp/common/types/v2/DynamicTypesCollectionPubSubTypes.cpp;
/build/DDS-Record-Replay-0.3.0/ddsrecorder_participants/src/cpp/common/types/v2/DynamicTypesCollectionv1.cpp;
/build/DDS-Record-Replay-0.3.0/ddsrecorder_participants/src/cpp/recorder/mcap/McapHandler.cpp;
/build/DDS-Record-Replay-0.3.0/ddsrecorder_participants/src/cpp/replayer/McapReaderParticipant.cpp;
/build/DDS-Record-Replay-0.3.0/ddsrecorder_participants/src/cpp/replayer/ReplayerParticipant.cpp
```
Which is why I suspect the compile_library.cmake

**Comment by rsanchez15** [comment]
Hi @paulBismuthListen 

Those are the versions that we are currently testing in our CI. I've tried to build it locally just in case there was something wrong in the CI but it also compiles locally. Have you tried to clean your workspace? Just in case you are linking against an old version of Fast DDS.

**Comment by paulBismuthListen** [comment]
Ok so cleaned my linux and build environement.
Switched to a local build (all dds related stuff built under same folder) instead of building one package then install it on /usr/local/.

Now compilation goes till the end, sorry for the troubles and thanks for the help-> closing this issue
