### ISSUE TITLE
Interoperability with other DDS implementations

### ISSUE THREAD

**Issue by spiderkeys** [eProsima/DDS-Record-Replay#125]
I gave the Recorder a try with RTI's shapes demo and found that while something seemed to end up recorded in the mcap, it was unloadable within Foxglove, which gave an error that the Shapes type schema was missing when I imported the file. I tried various permutations of these settings within my config file, but it didn't change anything:
```yaml
record-types: true
ros2-types: true
```

I don't know if this is an issue between eProsima's Recorder and Foxglove, or between RTI Connext (or one of its protocol-related QOS policies) and eProsima DDS and/or Recorder.

I also didn't necessarily expect Recorder to be compatible with other vendors, but I was hoping it would work with Connext and/or Cyclone, as we work with orgs/software that could use any of the three major implementations.

If this isn't a Foxglove specific thing, could someone share the DDS standard specifications/features/QOS policy configurations that Recorder requires to properly function?

Thanks!

**Comment by JaimeMartin** [comment]
Our DDS Record and replay does not support other DDS implementations.
