### ISSUE TITLE
requirement

### ISSUE THREAD

**Issue by 263868161** [eProsima/DDS-Record-Replay#57]
1 ddsrecorder should be  customize the file storage path individually.
2 ddsrecorder_controller should be  possible to customize the filename remotely.
3 ddsrecorder should be possible to set the initialization state,for example, the initial state is stop.
Thank you!

**Comment by rsanchez15** [comment]
Hi @263868161, 

I do not understand your requirements about DDS Record & Replay. Could you please specify a little bit more about what do you mean by listing these tree points here?

Just to clarify, points [1](https://dds-recorder.readthedocs.io/en/latest/rst/recording/usage/configuration.html#output-file) and [3](https://dds-recorder.readthedocs.io/en/latest/rst/recording/usage/configuration.html#remote-controller) are now covered by the DDS Record & Replay.
