### ISSUE TITLE
.mcap cannot be displayed in foxglove studio

### ISSUE THREAD

**Issue by 263868161** [eProsima/DDS-Record-Replay#76]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

.mcap is displayed normally in foxglove studio

### Current behavior

When I use foxglove studio to play back mcap files, some can be displayed normally, while others cannot.

### Steps to reproduce

1.Execute the fastddsgen command to generate idl code.(./fastddsgen *.idl -typeobject)
2.Copy the generated code to the shapes-demo code project and compile it
3../ShapeDemo
![image](https://github.com/eProsima/Fast-DDS/assets/20036253/73807e0e-cf08-4b5a-825b-e810dde3cd28)

4../ddsrecorder
![image](https://github.com/eProsima/Fast-DDS/assets/20036253/a0e2f20e-5f61-4bbe-8ded-f4ad4a3f1719)

5.Use foxglove studio to play back .mcap files
![image](https://github.com/eProsima/Fast-DDS/assets/20036253/154c929e-d55b-482c-8c57-f9c65ff25f85)

[issues.zip](https://github.com/eProsima/Fast-DDS/files/12290068/issues.zip)

### Fast DDS version/commit

fastdds:2.11.0
foxglove studio:1.64.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by juanlofer-eprosima** [comment]
Hi @263868161 

We would need to know more information in order to help you.

- What version of ShapesDemo is being run? Are you compiling it or taking it from a Docker image / runner?
- Why are you generating the types? The code related to dynamic types for Shape is already present.
- Which idl are you using as input? It seems like you added the ``ros2_interface::msg`` namespace right?

**Comment by 263868161** [comment]
> Hi @263868161
> 
> We would need to know more information in order to help you.
> 
> * What version of ShapesDemo is being run? Are you compiling it or taking it from a Docker image / runner?
version:2.11.1,compiling it.
> * Why are you generating the types? The code related to dynamic types for Shape is already present.
I want to do some different tests.
> * Which idl are you using as input? It seems like you added the `ros2_interface::msg` namespace right?
I added the `ros2_interface::msg` namespace myself,I used three IDL files,'Shape.idl','Header.idl',and 'Time.idl',Shape.idl is the main IDL file,'Shape.idl' contains 'Header.idl',Header.idl contains 'Time.idl',When the ShapeDemp  is running,the data of ‘Shape.idl‘ will be sent.

**Comment by 263868161** [comment]
My project has been uploaded as an attachment, which contains the IDL file

**Comment by rookybird** [comment]
I met the same issue. Record and Replay works well. But foxglove can not process my mcap file. 

![image](https://github.com/eProsima/DDS-Record-Replay/assets/120717938/2753f45c-0300-4849-9058-7ccebe7234d8)
Any hints?

**Comment by juanlofer-eprosima** [comment]
> I met the same issue. Record and Replay works well. But foxglove can not process my mcap file.
> 
> ![image](https://private-user-images.githubusercontent.com/120717938/286849282-2753f45c-0300-4849-9058-7ccebe7234d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjU3ODQsIm5iZiI6MTcwMTQyNTQ4NCwicGF0aCI6Ii8xMjA3MTc5MzgvMjg2ODQ5MjgyLTI3NTNmNDVjLTAzMDAtNDg0OS05MDU4LTdjY2ViZTcyMzRkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMVQxMDExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmZmZWFjN2NjNDEyNzhkYWFiM2JjOGQ5ZGU3NjgxZTk0NWU2ZWYzMGZkYWYyOGQ2YWRkNzViZWVlZGVlZDUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ASyQwlBQe3GcuPXAbHJG3DXoF_NXyOM586kZW3rWOzk) Any hints?

Hi @rookybird , this again looks like the recorder has not received the type information Foxglove requires for visualizing these topics. Are you sure your applications are generating and sending this type information? Please read [this tutorial](https://dds-recorder.readthedocs.io/en/latest/rst/tutorials/dynamic_types.html) for more details, and open a different issue if needed.
