### ISSUE TITLE
Main does not build with latest FastDDS & FastCDR

### ISSUE THREAD

**Issue by andrei-ng** [eProsima/DDS-Record-Replay#92]
Unable to build `main` with latest FastDDS (Fast DDS v2.12.0) and latest Fast-CDR (Fast CDR v2.0.0) due to major changes in CDR.

Any plans for an upcoming release to support Fast CDR v2.0.0 ?

**Comment by rsanchez15** [comment]
Hi @andrei-ng,

Right now we are working on Fast DDS v2.12.1 which will support backwards compatibility with Fast CDR v1.1.x. Once we have this, we will update DDS Record & Replay to work with latest versions of Fast DDS and Fast CDR.

The new version of Fast DDS is scheduled for release in two weeks, and as soon as it comes out we will bump the DDS Record & Replay version. Therefore we estimate that within two weeks you will have this updated tool available and supporting Fast CDR v2.0.0. 

In any case, do not close this issue and I will let you know as soon as it is available.

**Comment by andrei-ng** [comment]
@rsanchez15, that sounds great! Thank you for the update!

**Comment by juanlofer-eprosima** [comment]
Hi @andrei-ng , feel free to update Fast-DDS to its latest version as it is now compatible with `main`. Kind regards!

**Comment by andrei-ng** [comment]
> Hi @andrei-ng , feel free to update Fast-DDS to its latest version as it is now compatible with `main`. Kind regards!

Thank you @juanlofer-eprosima !
